### ISSUE TITLE
SafeExamBrowser on Windows 10s (Windows Store via "Desktop App Converter")

### ISSUE THREAD

**Issue by chrisjacob** [SafeExamBrowser/seb-win#24] opened 2017-11-15 23:28 UTC
# SafeExamBrowser on Windows 10s / Windows Store via "Desktop App Converter"

### Description

Background: We're working on a SEB-Win v2.1.3 branch for a custom built app.

The upcoming [Windows 10S](https://www.microsoft.com/en-au/windows/windows-10-s) platform will only support installing apps from the Windows Store.

To help convert existing apps to a Windows Store compatible app Microsoft provides a tool called "Desktop App Converter":

https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter
https://developer.microsoft.com/en-us/windows/bridges/desktop

In the current SEB .MSI and Service Manager post install, a Window Service is installed called “SEB Windows Service”. 

Unfortunately, Windows services are not supported when run in the full trust / UWP environment. The documentation [here](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare), gives a list of steps that should be taken to prep an app for UWP packaging. The following item applies here:

> **Your app requires a kernel-mode driver or a Windows service.** The bridge is suitable for an app, but **it does not support a kernel-mode driver or a Windows service** that needs to run under a system account. Instead of a Windows service, use a [background task](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-a-background-task).

It's worth mentioning that disabling the SEB Windows Service is possible as outlined [here](https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane): 

> **SEB Service policy:** The SEB Service is a background process running with elevated privileges (as administrator), which is necessary to block and unblock some system features (the options in the Windows Security Screen invoked by Ctrl-Alt-Del) and pausing Windows Update. SEB Windows Service is installed automatically together with the SEB application and started afterwards, but it might happen in rare cases that the service gets stopped. After a reboot of the computer it should get started again, also you could use Windows Task Manager to restart the service manualy (in the Services tab). 
> You can define the policy that applies when an exam client doesn't have the SEB Service running:
> - **allow to use SEB without service:** SEB is allowed to run without the SEB Service running, it will only be noted in the log that the service was not securing the computer during the exam.
> - **warn when service is not running:** A warning is displayed when the service is not running, but the exam can be started.
> - **allow to use SEB only with service:** SEB is only allowed to run when the SEB Service is running. 

... **however** turning off the Windows Service reduces the security of SEB.

Because a Windows Store app won't allow a Windows Service, it will not be possible to install SEB on a Windows 10S machine.

Windows 10S will be a popular OS in the Education market so this is particularly important to the SEB Project.

Aside from Windows 10S, it would also be beneficial to have the app on the Windows Store for distribution to other Windows 10 users.

So..... 

**Can the Windows Service be replaced with a Background Task that performs the same functionality (i.e. security is not reduced)?** 

**....And when running the app through "Desktop App Converter" can it switch over automatically to using the Background Task?**

### Environment & Version

Windows 10 / Windows 10S

- [ ] Mac
- [x] Windows

OS-Version: 10
SEB-Version: 2.1.3

### Steps to Reproduce

N/A

**Comment by dbuechel** [comment] 2017-11-16 10:25
_First off: I am not an UWP app developer and have unfortunately no experience with said technology. But I'll nonetheless try to reply to your questions to the best of my knowledge._

From what I have learned by reading the links you provided and via a quick internet research, the Desktop App Converter will most likely fail to build an app package for SEB. As far as I understood, one of Microsoft's goal with UWP was to encapsule applications in a sandbox-like environment, by e.g. restricting access to system resources / APIs (especially for Windows Store apps). SEB however uses a lot of native Win32-API calls and manipulates the registry.
Regarding the Windows Service: As far as I can see, SEB's WCF service would need to be rewritten as Background Task. The background task would need to continuously run with elevated privileges to manipulate the registry, and I'm not sure whether that's even possible or meaningful in the context of UWP.

Overall, I don't see an easy way to port SEB to UWP. On the contrary, I think SEB in its current form is not compatible with the idea of the Universal Windows Platform. I can see only one proper way to port SEB to UWP, which basically would be to completely rewrite SEB for UWP, replacing all the current functionality related to locking down the OS (disabling the explorer shell, window monitoring, mouse and keyboard interception etc.) with Windows 10's new "Take an Exam" mode for UWP apps and just keeping the UI and browser functionality. That SEB's third-party application functionality would still work in that scenario is highly unlikely, and whether a background task could remove all the options of the Security Screen as the WCF service currently does would also need to be evaluated.

Let me know if you have any other questions, otherwise I'd suggest to close this issue as we currently do not have the ressources to properly evaluate (let alone implement) an UWP solution...

**Comment by danschlet** [comment] 2017-11-16 14:09
I can confirm the previous reply. It won't be possible to do the same things SEB's WCF Service can do, like removing TaskManager, Shutdown, Restart etc. from the Windows Security Screen (invoked by Ctrl-Alt-Delete), because even those background task cannot elevate privileges. The WCF Service of SEB runs with administrator rights, this is necessary to change Registry settings for HKEY_LOCAL_MACHINE.

As you can see for example [here](https://windowsadmins.com/choosing-the-path-forward-for-existing-desktop-apps/), a background task can't change Registry key/values for HKEY_LOCAL_MACHINE.

I anyways don't understand why Ctrl-Alt-Delete can be used to exit the new single app kiosk mode in Windows 10/8. Like this the kiosk mode is quite useless, at least for BYOD scenarios.

**Closed** 2018-01-16 13:31 UTC
