### ISSUE TITLE
Autostart not working for third party application

### ISSUE THREAD

**Issue by j-pillon** [SafeExamBrowser/seb-win#25] opened 2017-11-20 10:18 UTC
# Autostart not working for third party application

### Description

I use SEB in kiosk mode to automatically launch a specific application for psychological testing. The "Autostart" configuration for the concerned process works in version 2.1.6 but not in version 2.1.7. The application is a heavy client (EXE) compiled under VB6 that communicates by socket (winsock) to a supervision application.

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: 6.1.7601 (Windows 7 Pro SP1) \
SEB-Version: 2.1.7

### Steps to Reproduce

1. Create a new SEB config
2. In User Interface tab, uncheck "Show SEB task bar"
3. In Browser tab, check "Use SEB without browser window"
4. In Security tab, set Kiosk Mode as "Create new desktop"
5. In Applications tab, leave "Monitor processes while SEB is running" checked
6. Add a permitted process :
6.1. Check "Active"
6.2. Fill "Title", "Executable" and "Path"
6.3. Check "Autostart" and "Force quit"
7. Save config
8. Create a shortcut in start menu, startup to launch SEB config at startup
9. Close and re-open session or reboot computer

**Comment by danschlet** [comment] 2017-11-20 11:08
In SEB 2.1.7 we made process monitoring more secure with tighter checking of executable and original name strings. Maybe you need to set the new permitted processes property "original name" correctly, especially if your application was renamed (you can check that in Windows Explorer right click Properties / Details).

Otherwise send us the SebClient.log file, [here](https://www.safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane)'s the information where to find it.

**Comment by j-pillon** [comment] 2017-11-20 14:03
Here is the SebClient.log file content. I only change user, server file and share names.

Third party application file name, original name and process name are the same. The exe works if I launch it from task bar.


20/11/2017 14:23:15 [Information]: SEB version: 2.1.6479.21233

20/11/2017 14:23:15 [Information]: ---------- INITIALIZING SEB - STARTING SESSION -------------

20/11/2017 14:23:15 [Information]:  Arguments: C:\Program Files (x86)\SafeExamBrowser\SafeExamBrowser.exe, \\my-server\share$\myconfig.seb

20/11/2017 14:23:15 [Information]: Attempting to InitSebSettings

20/11/2017 14:23:15 [Information]: SEB version: 2.1.6479.21233

20/11/2017 14:23:15 [Error]: Could not load SebClientSettigs.seb from the Program Data directorySystem.IO.FileNotFoundExceptionLe fichier 'd:\ProgramData\SafeExamBrowser\SebClientSettings.seb' est introuvable.

20/11/2017 14:23:15 [Information]: User Name: my.username Host Name: localhost Port Number: 57016 Send Interval: 100 Recv Timeout: 100 Num Messages: 3 SebClientConfigFileDirectory: d:\Users\my.username\AppData\Roaming\SafeExamBrowser\ SebClientConfigFile: d:\Users\my.username\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb

20/11/2017 14:23:15 [Information]: SEB client configuration set in InitSebSettings().

20/11/2017 14:23:15 [Information]: OS Version: 2050

20/11/2017 14:23:15 [Information]: Successfully InitSebSettings

20/11/2017 14:23:15 [Information]: OnLoad EventArgs: C:\Program Files (x86)\SafeExamBrowser\SafeExamBrowser.exe, \\my-server\share$\myconfig.seb

20/11/2017 14:23:15 [Information]: Attempting to read new configuration file

20/11/2017 14:23:15 [Information]: Succesfully read the new configuration, length is 19456

20/11/2017 14:23:15 [Information]: Attempting to StoreDecryptedSEBSettings

20/11/2017 14:23:15 [Information]: Reconfiguring

20/11/2017 14:23:15 [Information]: Attempting to CloseSEBForm for reconfiguration

20/11/2017 14:23:15 [Information]: Restoring Registry entries

20/11/2017 14:23:15 [Information]: initializing wcf service connection

20/11/2017 14:23:15 [Information]: Username from Environment = my.username

20/11/2017 14:23:15 [Information]: SEB Windows service available

20/11/2017 14:23:15 [Information]: Windows Service is available

20/11/2017 14:23:15 [Information]: resetting registry entries

20/11/2017 14:23:15 [Information]: calling reset on wcf service

20/11/2017 14:23:16 [Information]: Attempting to reset workspacearea

20/11/2017 14:23:16 [Information]: Aorkspace area resetted

20/11/2017 14:23:16 [Information]: Closing processes that where started by SEB

20/11/2017 14:23:16 [Information]: Clearing running processes list

20/11/2017 14:23:16 [Information]: Disabling foreground watchdog

20/11/2017 14:23:16 [Information]: Disabling process watchdog

20/11/2017 14:23:16 [Information]: Restoring hidden windows

20/11/2017 14:23:16 [Information]: Clipboard deleted.

20/11/2017 14:23:16 [Information]: Disabling filtered keys

20/11/2017 14:23:16 [Information]: Returning from closesebform

20/11/2017 14:23:16 [Information]: Succesfully CloseSEBForm for reconfiguration

20/11/2017 14:23:16 [Information]: Reconfiguring to start an exam

20/11/2017 14:23:16 [Information]: Attempting to StoreSebClientSettings

20/11/2017 14:23:16 [Information]: Successfully StoreSebClientSettings

20/11/2017 14:23:16 [Information]: SEB version: 2.1.6479.21233

20/11/2017 14:23:16 [Information]: Attemting to InitSEBDesktop for reconfiguration

20/11/2017 14:23:16 [Information]: Attempting to InitSEBDesktop

20/11/2017 14:23:16 [Information]: Clipboard cleaned.

20/11/2017 14:23:17 [Information]: Process 'C:\Windows\explorer.exe' has been renamed from 'EXPLORER.EXE' to 'explorer'!

20/11/2017 14:23:17 [Information]: Window for process 'explorer' is not allowed!

20/11/2017 14:23:17 [Information]: Window Démarrer SW_SHOWMINIMIZED

20/11/2017 14:23:17 [Information]: Successfully InitSEBDesktop

20/11/2017 14:23:17 [Information]: Sucessfully InitSEBDesktop for reconfiguration

20/11/2017 14:23:17 [Information]: Attempting to OpenSEBForm for reconfiguration

20/11/2017 14:23:17 [Information]: Entering OpenSEBForm

20/11/2017 14:23:17 [Information]: Hiding the taskbar

20/11/2017 14:23:17 [Information]: Win32_ComputerSystem Manufacturer: LENOVO, Model: 10953A0

20/11/2017 14:23:17 [Information]: SEB Windows service available

20/11/2017 14:23:17 [Information]: Setting registry values

20/11/2017 14:23:17 [Information]: SEB Windows service available

20/11/2017 14:23:18 [Information]: Disabling Windows update

20/11/2017 14:23:18 [Information]: SEB Windows service available

20/11/2017 14:23:18 [Information]: calling disable windows update on wcf service

20/11/2017 14:23:18 [Information]: Killing processes that are not allowed to run

20/11/2017 14:23:19 [Information]: Process 'C:\Windows\explorer.exe' has been renamed from 'EXPLORER.EXE' to 'explorer'!

20/11/2017 14:23:21 [Information]: Process 'C:\Program Files\Realtek\Audio\HDA\RAVCpl64.exe' has been renamed from 'RtHDVCpl' to 'RAVCpl64'!

20/11/2017 14:23:21 [Information]: Attempting to start socket server

20/11/2017 14:23:21 [Information]: Starting WebSocketServer on ws://localhost:8706

20/11/2017 14:23:21 [Information]: Started WebSocketServer on ws://localhost:8706

20/11/2017 14:23:22 [Information]: Adding allowed processes to taskbar

20/11/2017 14:23:22 [Information]: Creating close dialog form

20/11/2017 14:23:22 [Information]: Building application chooser form

20/11/2017 14:23:22 [Information]: Successfully OpenSEBForm for reconfiguration

20/11/2017 14:23:22 [Information]: Successfully StoreDecryptedSEBSettings

20/11/2017 14:23:22 [Information]: Window for process 'Idle' is not allowed!

20/11/2017 14:23:22 [Information]: Window  closed, because i was unable to hide it

20/11/2017 14:23:22 [Information]: Window for process 'Idle' is not allowed!

20/11/2017 14:23:22 [Information]: Window  closed, because i was unable to hide it

20/11/2017 14:23:22 [Information]: Window for process 'Idle' is not allowed!

20/11/2017 14:23:22 [Information]: Window  closed, because i was unable to hide it

20/11/2017 14:32:53 [Information]: Attempting to CloseSEBForm in ExitApplication

20/11/2017 14:32:53 [Information]: Restoring Registry entries

20/11/2017 14:32:53 [Information]: SEB Windows service available

20/11/2017 14:32:53 [Information]: Windows Service is available

20/11/2017 14:32:53 [Information]: resetting registry entries

20/11/2017 14:32:53 [Information]: calling reset on wcf service

20/11/2017 14:32:53 [Information]: Attempting to reset workspacearea

20/11/2017 14:32:54 [Information]: Aorkspace area resetted

20/11/2017 14:32:54 [Information]: Closing processes that where started by SEB

20/11/2017 14:32:54 [Information]: Clearing running processes list

20/11/2017 14:32:54 [Information]: Disabling foreground watchdog

20/11/2017 14:32:54 [Information]: Disabling process watchdog

20/11/2017 14:32:54 [Information]: Restoring hidden windows

20/11/2017 14:32:54 [Information]: Attempting to start Explorer Shell

20/11/2017 14:32:54 [Information]: waiting for explorer shell to get up 0 seconds

20/11/2017 14:32:55 [Information]: waiting for explorer shell to get up 1 seconds

20/11/2017 14:32:55 [Information]: waiting for explorer shell to finish starting 6 seconds

20/11/2017 14:33:01 [Information]: Successfully started Explorer Shell

20/11/2017 14:33:01 [Information]: Clipboard deleted.

20/11/2017 14:33:01 [Information]: Disabling filtered keys

20/11/2017 14:33:01 [Information]: Returning from closesebform

20/11/2017 14:33:01 [Information]: Successfull CloseSEBForm

20/11/2017 14:33:01 [Information]: closing loading screen

20/11/2017 14:33:01 [Information]: shutting down loading screen

20/11/2017 14:33:01 [Information]: loading screen shut down

20/11/2017 14:33:01 [Information]: Attempting to ResetSEBDesktop in ExitApplication

20/11/2017 14:33:01 [Information]: Successfull ResetSEBDesktop

20/11/2017 14:33:01 [Information]: ---------- EXITING SEB - ENDING SESSION -------------

**Comment by danschlet** [comment] 2017-11-20 14:44
I should have asked for more details, like what's the executable's name, otherwise the log isn't very helpful. But looking at the code, it seems like there are no log commands at the interesting spots. 

Can you also send the SEB config file you are using? You can remove all passwords and server addresses for privacy (or send it as a private message on our [SourceForge project site](https://sourceforge.net/p/seb/bugs/), unfortunately GitHub thinks pm's are not necessary). But please try first if the stripped config file still has that problem.

You can also test if it works with [SEB 2.1.8](https://github.com/SafeExamBrowser/seb-testing/tree/master/win/2.1.8). It's release will happen anytime from now, I hope the issue doesn't appear in 2.1.8 anymore, as it would probably be too late to fix it for that version.

**Comment by danschlet** [comment] 2017-11-20 15:19
Btw., did you try to select the process executable in SEB Config Tool using the "Choose Application" button? You mentioned you filled "Path" manually. Path isn't necessary to be set for most applications, if they are installed and registered in the system, Windows already has the correct path. Only in some cases path has to be set, like when the executable is in a sub-directory of the software. When using the "Choose Application" button, SEB finds out itself if a path entry is necessary and fills it if yes. Manually settings a path if it's not necessary might have erratic effects.

**Comment by j-pillon** [comment] 2017-11-21 10:10
First of all, thank you for your reactivity !

I tried to reproduce my problem with "standard" exe. So, I allowed 7-zip, Firefox (added in allowed processes and unchecked in prohibited processes) and VLC, all with the "Choose Application ..." button. Also, I left XULRunner.exe as a allowed process.
The resulting SEB file is at the end of this message.

Then, I changed the "Autostart" property of the different exe by trying all the possible configurations: the processes actually started are always shifted by one line compared to the table of permitted processes.

In the example of the configuration below, if I check "Autostart" only for Firefox, it is 7-zip that starts automatically.

Same results with 2.1.8 beta.

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>originatorVersion</key>
    <string>SEB_Win_2.1.1</string>
    <key>startURL</key>
    <string />
    <key>sebServerURL</key>
    <string />
    <key>hashedAdminPassword</key>
    <string />
    <key>allowQuit</key>
    <true />
    <key>ignoreExitKeys</key>
    <true />
    <key>hashedQuitPassword</key>
    <string />
    <key>exitKey1</key>
    <integer>11</integer>
    <key>exitKey2</key>
    <integer>10</integer>
    <key>exitKey3</key>
    <integer>9</integer>
    <key>sebMode</key>
    <integer>0</integer>
    <key>browserMessagingSocket</key>
    <string>ws://localhost:8706</string>
    <key>browserMessagingPingTime</key>
    <integer>120000</integer>
    <key>sebConfigPurpose</key>
    <integer>0</integer>
    <key>allowPreferencesWindow</key>
    <true />
    <key>browserViewMode</key>
    <integer>1</integer>
    <key>mainBrowserWindowWidth</key>
    <string>100%</string>
    <key>mainBrowserWindowHeight</key>
    <string>100%</string>
    <key>mainBrowserWindowPositioning</key>
    <integer>1</integer>
    <key>enableBrowserWindowToolbar</key>
    <false />
    <key>hideBrowserWindowToolbar</key>
    <false />
    <key>showMenuBar</key>
    <false />
    <key>showTaskBar</key>
    <false />
    <key>taskBarHeight</key>
    <integer>40</integer>
    <key>touchOptimized</key>
    <false />
    <key>enableZoomText</key>
    <true />
    <key>enableZoomPage</key>
    <true />
    <key>zoomMode</key>
    <integer>0</integer>
    <key>allowSpellCheck</key>
    <false />
    <key>allowDictionaryLookup</key>
    <false />
    <key>showTime</key>
    <false />
    <key>showInputLanguage</key>
    <false />
    <key>enableTouchExit</key>
    <false />
    <key>oskBehavior</key>
    <integer>2</integer>
    <key>browserScreenKeyboard</key>
    <false />
    <key>newBrowserWindowByLinkPolicy</key>
    <integer>1</integer>
    <key>newBrowserWindowByScriptPolicy</key>
    <integer>2</integer>
    <key>newBrowserWindowByLinkBlockForeign</key>
    <false />
    <key>newBrowserWindowByScriptBlockForeign</key>
    <false />
    <key>newBrowserWindowByLinkWidth</key>
    <string>100%</string>
    <key>newBrowserWindowByLinkHeight</key>
    <string>100%</string>
    <key>newBrowserWindowByLinkPositioning</key>
    <integer>2</integer>
    <key>enablePlugIns</key>
    <true />
    <key>enableJava</key>
    <false />
    <key>enableJavaScript</key>
    <true />
    <key>blockPopUpWindows</key>
    <false />
    <key>allowBrowsingBackForward</key>
    <false />
    <key>removeBrowserProfile</key>
    <true />
    <key>removeLocalStorage</key>
    <true />
    <key>enableSebBrowser</key>
    <false />
    <key>showReloadButton</key>
    <false />
    <key>showReloadWarning</key>
    <true />
    <key>browserUserAgentWinDesktopMode</key>
    <integer>0</integer>
    <key>browserUserAgentWinDesktopModeCustom</key>
    <string />
    <key>browserUserAgentWinTouchMode</key>
    <integer>0</integer>
    <key>browserUserAgentWinTouchModeCustom</key>
    <string />
    <key>browserUserAgent</key>
    <string />
    <key>browserUserAgentMac</key>
    <integer>0</integer>
    <key>browserUserAgentMacCustom</key>
    <string />
    <key>allowDownUploads</key>
    <true />
    <key>downloadDirectoryOSX</key>
    <string>~/Downloads</string>
    <key>downloadDirectoryWin</key>
    <string />
    <key>openDownloads</key>
    <false />
    <key>chooseFileToUploadPolicy</key>
    <integer>0</integer>
    <key>downloadPDFFiles</key>
    <false />
    <key>allowPDFPlugIn</key>
    <false />
    <key>downloadAndOpenSebConfig</key>
    <true />
    <key>examKeySalt</key>
    <data>f9tMlvYt7Hh/9WQawIJo59cNmBEZLJ1UT9TX2h3iFa8=</data>
    <key>browserExamKey</key>
    <string />
    <key>browserURLSalt</key>
    <true />
    <key>sendBrowserExamKey</key>
    <false />
    <key>quitURL</key>
    <string />
    <key>restartExamURL</key>
    <string />
    <key>restartExamUseStartURL</key>
    <false />
    <key>restartExamText</key>
    <string />
    <key>restartExamPasswordProtected</key>
    <true />
    <key>monitorProcesses</key>
    <true />
    <key>allowSwitchToApplications</key>
    <false />
    <key>allowFlashFullscreen</key>
    <false />
    <key>permittedProcesses</key>
    <array>
      <dict>
        <key>active</key>
        <true />
        <key>autostart</key>
        <false />
        <key>iconInTaskbar</key>
        <false />
        <key>runInBackground</key>
        <false />
        <key>allowUserToChooseApp</key>
        <false />
        <key>strongKill</key>
        <true />
        <key>os</key>
        <integer>1</integer>
        <key>title</key>
        <string>SEB</string>
        <key>description</key>
        <string />
        <key>executable</key>
        <string>xulrunner.exe</string>
        <key>path</key>
        <string>../xulrunner/</string>
        <key>identifier</key>
        <string>XULRunner</string>
        <key>windowHandlingProcess</key>
        <string />
        <key>arguments</key>
        <array></array>
        <key>originalName</key>
        <string />
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>autostart</key>
        <true />
        <key>iconInTaskbar</key>
        <false />
        <key>runInBackground</key>
        <false />
        <key>allowUserToChooseApp</key>
        <false />
        <key>strongKill</key>
        <true />
        <key>os</key>
        <integer>1</integer>
        <key>title</key>
        <string>7zFM</string>
        <key>description</key>
        <string />
        <key>executable</key>
        <string>7zfm.exe</string>
        <key>originalName</key>
        <string>7zFM.exe</string>
        <key>windowHandlingProcess</key>
        <string />
        <key>path</key>
        <string />
        <key>identifier</key>
        <string />
        <key>arguments</key>
        <array></array>
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>autostart</key>
        <true />
        <key>iconInTaskbar</key>
        <false />
        <key>runInBackground</key>
        <false />
        <key>allowUserToChooseApp</key>
        <false />
        <key>strongKill</key>
        <true />
        <key>os</key>
        <integer>1</integer>
        <key>title</key>
        <string>firefox</string>
        <key>description</key>
        <string />
        <key>executable</key>
        <string>firefox.exe</string>
        <key>originalName</key>
        <string>firefox.exe</string>
        <key>windowHandlingProcess</key>
        <string />
        <key>path</key>
        <string />
        <key>identifier</key>
        <string />
        <key>arguments</key>
        <array></array>
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>autostart</key>
        <true />
        <key>iconInTaskbar</key>
        <false />
        <key>runInBackground</key>
        <false />
        <key>allowUserToChooseApp</key>
        <false />
        <key>strongKill</key>
        <true />
        <key>os</key>
        <integer>1</integer>
        <key>title</key>
        <string>vlc</string>
        <key>description</key>
        <string />
        <key>executable</key>
        <string>vlc.exe</string>
        <key>originalName</key>
        <string>vlc.exe</string>
        <key>windowHandlingProcess</key>
        <string />
        <key>path</key>
        <string />
        <key>identifier</key>
        <string />
        <key>arguments</key>
        <array></array>
      </dict>
    </array>
    <key>prohibitedProcesses</key>
    <array>
      <dict>
        <key>active</key>
        <false />
        <key>currentUser</key>
        <true />
        <key>strongKill</key>
        <false />
        <key>os</key>
        <integer>1</integer>
        <key>executable</key>
        <string>Firefox</string>
        <key>originalName</key>
        <string>Firefox</string>
        <key>description</key>
        <string />
        <key>identifier</key>
        <string />
        <key>windowHandlingProcess</key>
        <string />
        <key>user</key>
        <string />
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>currentUser</key>
        <true />
        <key>strongKill</key>
        <false />
        <key>os</key>
        <integer>1</integer>
        <key>executable</key>
        <string>UCBrowser</string>
        <key>originalName</key>
        <string>UCBrowser</string>
        <key>description</key>
        <string />
        <key>identifier</key>
        <string />
        <key>windowHandlingProcess</key>
        <string />
        <key>user</key>
        <string />
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>currentUser</key>
        <true />
        <key>strongKill</key>
        <false />
        <key>os</key>
        <integer>1</integer>
        <key>executable</key>
        <string>slimjet</string>
        <key>originalName</key>
        <string>slimjet</string>
        <key>description</key>
        <string />
        <key>identifier</key>
        <string />
        <key>windowHandlingProcess</key>
        <string />
        <key>user</key>
        <string />
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>currentUser</key>
        <true />
        <key>strongKill</key>
        <false />
        <key>os</key>
        <integer>1</integer>
        <key>executable</key>
        <string>browser</string>
        <key>originalName</key>
        <string>browser</string>
        <key>description</key>
        <string />
        <key>identifier</key>
        <string />
        <key>windowHandlingProcess</key>
        <string />
        <key>user</key>
        <string />
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>currentUser</key>
        <true />
        <key>strongKill</key>
        <false />
        <key>os</key>
        <integer>1</integer>
        <key>executable</key>
        <string>Opera</string>
        <key>originalName</key>
        <string>Opera</string>
        <key>description</key>
        <string />
        <key>identifier</key>
        <string />
        <key>windowHandlingProcess</key>
        <string />
        <key>user</key>
        <string />
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>currentUser</key>
        <true />
        <key>strongKill</key>
        <false />
        <key>os</key>
        <integer>1</integer>
        <key>executable</key>
        <string>Vivaldi</string>
        <key>originalName</key>
        <string>Vivaldi</string>
        <key>description</key>
        <string />
        <key>identifier</key>
        <string />
        <key>windowHandlingProcess</key>
        <string />
        <key>user</key>
        <string />
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>currentUser</key>
        <true />
        <key>strongKill</key>
        <false />
        <key>os</key>
        <integer>1</integer>
        <key>executable</key>
        <string>Chromium</string>
        <key>originalName</key>
        <string>Chromium</string>
        <key>description</key>
        <string />
        <key>identifier</key>
        <string />
        <key>windowHandlingProcess</key>
        <string />
        <key>user</key>
        <string />
      </dict>
      <dict>
        <key>active</key>
        <true />
        <key>currentUser</key>
        <true />
        <key>strongKill</key>
        <false />
        <key>os</key>
        <integer>1</integer>
        <key>executable</key>
        <string>Chrome</string>
        <key>originalName</key>
        <string>Chrome</string>
        <key>description</key>
        <string />
        <key>identifier</key>
        <string />
        <key>windowHandlingProcess</key>
        <string />
        <key>user</key>
        <string />
      </dict>
    </array>
    <key>enableURLFilter</key>
    <false />
    <key>enableURLContentFilter</key>
    <false />
    <key>URLFilterRules</key>
    <array></array>
    <key>URLFilterEnable</key>
    <false />
    <key>URLFilterEnableContentFilter</key>
    <false />
    <key>blacklistURLFilter</key>
    <string />
    <key>whitelistURLFilter</key>
    <string />
    <key>urlFilterTrustedContent</key>
    <false />
    <key>urlFilterRegex</key>
    <false />
    <key>embeddedCertificates</key>
    <array></array>
    <key>proxySettingsPolicy</key>
    <integer>0</integer>
    <key>proxies</key>
    <dict>
      <key>ExceptionsList</key>
      <array></array>
      <key>ExcludeSimpleHostnames</key>
      <false />
      <key>AutoDiscoveryEnabled</key>
      <false />
      <key>AutoConfigurationEnabled</key>
      <false />
      <key>AutoConfigurationJavaScript</key>
      <string />
      <key>AutoConfigurationURL</key>
      <string />
      <key>FTPPassive</key>
      <true />
      <key>HTTPEnable</key>
      <false />
      <key>HTTPPort</key>
      <integer>80</integer>
      <key>HTTPProxy</key>
      <string />
      <key>HTTPRequiresPassword</key>
      <false />
      <key>HTTPUsername</key>
      <string />
      <key>HTTPPassword</key>
      <string />
      <key>HTTPSEnable</key>
      <false />
      <key>HTTPSPort</key>
      <integer>443</integer>
      <key>HTTPSProxy</key>
      <string />
      <key>HTTPSRequiresPassword</key>
      <false />
      <key>HTTPSUsername</key>
      <string />
      <key>HTTPSPassword</key>
      <string />
      <key>FTPEnable</key>
      <false />
      <key>FTPPort</key>
      <integer>21</integer>
      <key>FTPProxy</key>
      <string />
      <key>FTPRequiresPassword</key>
      <false />
      <key>FTPUsername</key>
      <string />
      <key>FTPPassword</key>
      <string />
      <key>SOCKSEnable</key>
      <false />
      <key>SOCKSPort</key>
      <integer>1080</integer>
      <key>SOCKSProxy</key>
      <string />
      <key>SOCKSRequiresPassword</key>
      <false />
      <key>SOCKSUsername</key>
      <string />
      <key>SOCKSPassword</key>
      <string />
      <key>RTSPEnable</key>
      <false />
      <key>RTSPPort</key>
      <integer>554</integer>
      <key>RTSPProxy</key>
      <string />
      <key>RTSPRequiresPassword</key>
      <false />
      <key>RTSPUsername</key>
      <string />
      <key>RTSPPassword</key>
      <string />
    </dict>
    <key>sebServicePolicy</key>
    <integer>1</integer>
    <key>allowVirtualMachine</key>
    <false />
    <key>createNewDesktop</key>
    <true />
    <key>killExplorerShell</key>
    <false />
    <key>allowUserSwitching</key>
    <true />
    <key>enableAppSwitcherCheck</key>
    <true />
    <key>forceAppFolderInstall</key>
    <true />
    <key>minMacOSVersion</key>
    <integer>0</integer>
    <key>allowDisplayMirroring</key>
    <false />
    <key>allowedDisplaysMaxNumber</key>
    <integer>1</integer>
    <key>allowedDisplayBuiltin</key>
    <true />
    <key>enableLogging</key>
    <true />
    <key>logDirectoryOSX</key>
    <string>~/Documents</string>
    <key>logDirectoryWin</key>
    <string />
    <key>allowWlan</key>
    <false />
    <key>insideSebEnableSwitchUser</key>
    <false />
    <key>insideSebEnableLockThisComputer</key>
    <false />
    <key>insideSebEnableChangeAPassword</key>
    <false />
    <key>insideSebEnableStartTaskManager</key>
    <false />
    <key>insideSebEnableLogOff</key>
    <false />
    <key>insideSebEnableShutDown</key>
    <false />
    <key>insideSebEnableEaseOfAccess</key>
    <false />
    <key>insideSebEnableVmWareClientShade</key>
    <false />
    <key>insideSebEnableEnableNetworkConnectionSelector</key>
    <false />
    <key>hookKeys</key>
    <true />
    <key>enableEsc</key>
    <false />
    <key>enableCtrlEsc</key>
    <false />
    <key>enableAltEsc</key>
    <false />
    <key>enableAltTab</key>
    <true />
    <key>enableAltF4</key>
    <false />
    <key>enableStartMenu</key>
    <false />
    <key>enableRightMouse</key>
    <false />
    <key>enablePrintScreen</key>
    <false />
    <key>enableAltMouseWheel</key>
    <false />
    <key>enableF1</key>
    <false />
    <key>enableF2</key>
    <false />
    <key>enableF3</key>
    <false />
    <key>enableF4</key>
    <false />
    <key>enableF5</key>
    <true />
    <key>enableF6</key>
    <false />
    <key>enableF7</key>
    <false />
    <key>enableF8</key>
    <false />
    <key>enableF9</key>
    <false />
    <key>enableF10</key>
    <false />
    <key>enableF11</key>
    <false />
    <key>enableF12</key>
    <false />
    <key>allowVideoCapture</key>
    <false />
    <key>allowAudioCapture</key>
    <false />
  </dict>
</plist>
```

**Comment by danschlet** [comment] 2017-11-21 14:54
Thank you as well for reporting this bug in this detail! I finally was able to track it down: The autostart property only didn't work when the SEB browser is deactivated ("Use SEB without browser window"), that's why I first couldn't reproduce it. The issue was introduced by another (incomplete) bugfix for autostart in SEB 2.1.7, which unfortunately wasn't tested properly.

I think now it should be fixed correctly in the updated SEB 2.1.8 version, at least my tests now work correctly. Would be great if you could re-test it and confirm if it works for you now as well.

**Comment by j-pillon** [comment] 2017-11-22 13:23
I have successfully tested version 2.1.8 beta GM3. However, I'm waiting for the 2.1.8 release before deployment.

Thank you

**Comment by danschlet** [comment] 2018-01-16 13:34
It works in SEB 2.1.8 and SEB 2.2.

**Closed by danschlet** 2018-01-16 13:34 UTC
