### ISSUE TITLE
Fresh install of SEB displays corrupted warning

### ISSUE THREAD

**Issue by Krisell** [SafeExamBrowser/seb-win#53] opened 2018-11-01 10:56 UTC
# Fresh install of SEB displays corrupted warning

### Description

When installing SEB 2.2.2 for Windows, I get a message saying that some files are left from a previous install. I have had previous versions on the same computer, but I have uninstalled, removed the folder, clean the trash-bin and also restarted before installing the new version – same problem.

### Environment & Version

Window 10 1709, HP
- [ ] Mac
- [x] Windows

SEB-Version: 2.2.2

### Steps to Reproduce

1. Make sure any previous installation of SEB is uninstalled.
2. Remove SafeExamBrowser-folder, including cleaning the trash-bin and restarting the system.
3. Install SEB 2.2.2
4. On launch, I get the "SEB installation is corrupted"-error.
5. I can close the error and continue, but I guess this may also result in problems with the BEK (not verified)?

**Comment by danschlet** [comment] 2018-11-01 11:04
Then you have some tool on your computer which adds files to the SEB program folder (malware?). What files are listed in the dialog? Always post full photos or text of error messages, THEN we can really analyze problems...

**Comment by Krisell** [comment] 2018-11-01 11:11
It's a long list of files and I can't scroll.

![img_1235](https://user-images.githubusercontent.com/25909128/47848546-f8aeb200-ddce-11e8-8fae-8e0731e2dbb6.JPG)

I noticed all files where in the /chrome/-directory, so I tried to remove that. I got a similar list with other files in the xul_seb-directory.

I know of one more person having the exact same issue.

**Comment by danschlet** [comment] 2018-11-01 11:16
If there were no files listed in the error message, send us SEBClient.log.

**Comment by danschlet** [comment] 2018-11-01 15:02
I think the first file is relevant, it is in a subdirectory called “sw”. Are you in Sweden? Maybe Firefox or pdf.js somehow downloads or unpacks language packs according to your locale. It’s important to never start the embedded Firefox in the SEB program directory (SebWindowsBrowser\xul_seb\) as it starts updating itself.

**Comment by Krisell** [comment] 2018-11-01 15:29
Yes, I'm in Sweden.

I have not started the embedded browser manually. After deleting the SafeExamBrowser directory, it is missing until I install SEB again.

If there is a problem with some update-process running in the background, what would I look for? The files in the SafeExamBrowser-directory does not seem to be touched though, they are created upon install and causes the problem on the first run.

**Comment by danschlet** [comment] 2018-11-01 16:08
Only files in the SebWindowsBrowser subdirectory can cause this error. The problem with Firefox and the seb2 XUL browser app is, that with additional files you can change the browser’s behavior, that’s why we can’t just ignore them for generating the key.

It’s quite sure the browser installs some additional stuff when run the first time, we have to find out how to stop that.

**Comment by danschlet** [comment] 2018-11-01 21:32
Even though I'm on vacation actually, I looked into this issue and figured out why it happens:

You guys in Sweden had some historical issues with the letters "v" and "w" I learned. Apparently those letters were considered to be identical or something like that. Whatever, but Windows with a Swedish locale sorts "w" before "v". That's why the Browser Exam Key is different depending on the Windows locale. In your SebClient.log the files were sorted like this:

`C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xul_seb\chrome\content\pdfjs\web\locale\sr\viewer.properties
C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xul_seb\chrome\content\pdfjs\web\locale\sw\viewer.properties
C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xul_seb\chrome\content\pdfjs\web\locale\sv-SE\viewer.properties
`

and in my default US-English Windows:
 
`C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xul_seb\chrome\content\pdfjs\web\locale\sr\viewer.properties
C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xul_seb\chrome\content\pdfjs\web\locale\sv-SE\viewer.properties
C:\Program Files (x86)\SafeExamBrowser\SebWindowsBrowser\xul_seb\chrome\content\pdfjs\web\locale\sw\viewer.properties
`
This wouldn't have happened if Microsoft wouldn't have had such a in my opinion brain dead idea that the ArrayList.Sort method should perform culture-sensitive behavior by default. Once again Apple does that way better, there you have clearly named operators (like "localizedCaseInsensitiveCompare").

So we can fix this in the next update (SEB 2.2.3) by using culture-insensitive sorting. I'll deal with this when I'm back in the office on November 8. Until we can release that, unfortunately you will have to live with this error message (and ignore it). If you have users with Windows set to different locales, you should generate two BEK, once set to Swedish, once set to en-US.

Btw. we would have found this out much earlier if SEB users which report issues would 
 help us to help them. Someone with Windows set to Turkish had a similar issue, I asked them to send us SebClient.log, but they never followed up. That's why only thorough bug reports are helpful, if people don't make the effort to send us all necessary information, then we often can't help.

**Comment by Krisell** [comment] 2018-11-02 08:44
Thank you very much danschlet for your investigation and information. We really appreciate all the great work you do and I'll try to spend more time test out upcoming versions.

**Comment by danschlet** [comment] 2018-11-15 11:11
The issue is fixed in the SEB 2.2.3 preview version, see the seb-testing repository.

**Comment by Krisell** [comment] 2018-11-20 13:56
I can confirm that this issue is resolved in 2.2.3pre2

**Closed** 2018-11-20 13:56 UTC
